---
k3s_version: v1.28.5+k3s1
ansible_user: harman
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
api_endpoint: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: '--write-kubeconfig-mode 644'
extra_agent_args: ''
token: "CHANGE_ME"