# Install traefik
---
- hosts: "master"
  become: true
  tasks:
  # Make sure pip3 is installed
  - name: install pip3
    apt:
      name: python3-pip
      state: present
      update_cache: yes
  # Make sure the following python packages are installed
  - name: install required pip packages
    pip:
      name:
        - kubernetes
        - pyyaml
        - jsonpatch
  # added the Traefik repo (i'm not sure if this will auto refresh)
  - name: Add helm repo
    kubernetes.core.helm_repository:
      name: stable
      repo_url: https://helm.traefik.io/traefik
  - name: Create namespace
    kubernetes.core.k8s:
      name: traefik
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: "~/.kube/config"