# Install traefik
---
- hosts: "master"
  become: true
  tasks:
    # Make sure pip3 is installed
    - name: install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    # Make sure the following python packages are installed
    - name: install required pip packages
      pip:
        name:
          - kubernetes
          - pyyaml
          - jsonpatch

    # added the Traefik repo (i'm not sure if this will auto refresh)
    - name: Add Traefik repo
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://traefik.github.io/charts

    # TODO: get the below working
    # helm -n kube-system delete traefik traefik-crd
    # kubectl -n kube-system delete helmchart traefik traefik-crd
    # touch /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
    # kubectl delete svc traefik -n kube-system
    # systemctl restart k3s

    # Deploy Traefik
    - name: Deploy latest version of traefik chart inside it's own namespace (and create it)
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        values: "{{ lookup('template', '~/projects/k3s-ansible/templates/traefik-config.yaml') | from_yaml }}"
        release_namespace: traefik
        create_namespace: true
        validate_certs: false
        kubeconfig: "/home/harman/.kube/config"
        wait: true

    - name: Deploy default headers
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '~/projects/k3s-ansible/templates/default-headers.yaml') | from_yaml }}"
        kubeconfig: "/home/harman/.kube/config"
        wait: true
    
    # Deploying the dashboard secret
    - name: Install the traefik dashboard
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '~/projects/k3s-ansible/templates/secret-dashboard.yaml') | from_yaml }}"
        kubeconfig: "/home/harman/.kube/config"

    # Deploying the dashboard middleware
    - name: Install the traefik middleware
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '~/projects/k3s-ansible/templates/middleware.yaml') | from_yaml }}"
        kubeconfig: "/home/harman/.kube/config"

    # Deploying the dashboard ingress
    - name: Install the traefik ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '~/projects/k3s-ansible/templates/traefik-ingress.yaml') | from_yaml }}"
        kubeconfig: "/home/harman/.kube/config"