# Update and upgrade apt packages
- hosts: "*"
  become: true
  tasks:
  - name: apt update and upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  # Use this to create a password for the traefik dashboard
  - name: Install apache2-utils
    apt:
      name: iptables
      state: present