---
- hosts: "*"
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: Set timezone and configure timesyncd
      shell: timedatectl set-timezone America/New_York

    - name: Install Nala package manager
      apt:
        name: nala
        state: present

    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Set zsh as default shell
      shell: "chsh -s $(which zsh)"

    - name: Install oh-my-zsh
      shell: "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

    - name: Update Plugins for oh-my-zsh
      shell: "sed 's/^plugins=.*/plugins=(git kubectl)/' /home/harman/.zshrc"