---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    # - role: raspberrypi

- name: Setup K3S master
  hosts: master
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S node
  hosts: node
  become: true
  roles:
    - role: k3s_agent
